### ISSUE TITLE
Getting errors while saving blobs

### ISSUE THREAD

**Issue by LukasAppleFan** [RossDarker/A5-A6X-Blobs-Dumper#1]
Hello,
So I have an iPhone 4s (iPhone4,1) on iOS 8.4 and I am trying to dump blobs. But when running the last part of the tool I get this : 
```
ERROR: Blob for LLB is invalid (crypto)
myblob.plist is BROKEN
```
The .SHSH file does seem to save on the desktop but I don't know if those errors are going to corrupt it.
Thanks

**Comment by iLumic** [comment]
Same here, iPhone 4s but on iOS 7.1 having that error when validating dumped plist against 7.1 iPSW. Tried with Odysseus as well using different custom iPSWs, OS's (Mavericks, Mojave, Windows), all return "ERROR: Blob for LLB is invalid (crypto)"

**Comment by LukasAppleFan** [comment]
And do you know if this will make my blobs unusable or it’s just an issue that can be ignored ?

**Comment by iLumic** [comment]
@LukasAppleFan Just to quote dayt0n (creator of Odysseus which this tool is based on): _"if your SHSH blobs and APTickets are invalid in any way, this restore will fail and you will be forced to upgrade to the latest signed firmware"_

On another note, can you check your manufacturing date using your serial number on this site? 
http://www.chipmunk.nl/cgi-fast/applemodel.cgi
There are models of the 4s manufactured after September 2012 that ship on iOS 6 and have hardware changes that make them incompatible with iOS 5. Mine's made in May of 2013 so it has those changes. Right now I'm thinking that might be the root of my issue. Wbu?

**Comment by LukasAppleFan** [comment]
According to this site my phone was made in January (week53) 2011, I think it's a bug and that it was made on January 2012 (during the week that is the last week of 2011 and the first week of 2012).

**Comment by RossDarker** [comment]
I've just reproduced the issue on my 4S too trying 6.1.3 blobs, with both this and using Odysseus manually too.
It could be something new but I'm not sure exactly what that is.

**Comment by RossDarker** [comment]
Blobs seem to work fine despite the errors!

**Comment by LukasAppleFan** [comment]
Ok thanks !

**Comment by OothecaPickle** [comment]
looks like this is caused by an expired certificate. try setting your system time back a few years (temporarily).
