### ISSUE TITLE
prepare doesn work (macOS Sierra)

### ISSUE THREAD

**Issue by ghost** [RossDarker/A5-A6X-Blobs-Dumper#2]
Calculating BuildID for iOS 6.1.3
Please wait...

curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect
cat: firmware: No such file or directory
cat: firmware: No such file or directory
iOS 6.1.3 does not exist for iPhone4,1!

**Comment by RossDarker** [comment]
See [troubleshooting](https://github.com/RossDarker/A5-A6X-Blobs-Dumper/wiki/Troubleshooting)
