### ISSUE TITLE
Error when trying to run ./patchipsw

### ISSUE THREAD

**Issue by 1BMPC** [RossDarker/A5-A6X-Blobs-Dumper#3]
When I run the command ./patchipsw iPhone4,1 192.168.1.5 I get the following output:

WINDOWS DETECTED
Build ID: 10B329
Model: iPhone4,1
Devcice IP: 192.168.1.5
mv: cannot stat '10B329.ipsw': No such file or directory
mv: cannot stat '11D257.ipsw': No such file or directory
Will attempt to extract baseband from device

If asked, type yes, then the default password is "alpine"

Unable to negotiate with 192.168.1.5 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss
E_PROTO
fish: Connecting to 192.168.1.5:22
fish: Waiting for initial line...

Couldn't connect to device, install OpenSSH from Cydia, or run: rm ~/.ssh/known_hosts, then try again.

How could I extract the necessary files manually or fix this SSH error?

**Comment by LegacyTweak6** [comment]
Try using the tip here https://github.com/RossDarker/A5-A6X-Blobs-Dumper/wiki/Troubleshooting#patchipsw-
